### PR TITLE
add Cpplint

### PR DESCRIPTION
**Pull request by landonr**

### CODE REVIEW

**Comment by landonr** [comment]
lol after all this work it doesn't care about indentation besides that it's spaces not tabs. i guess this is still a bit better

**Comment by abroooo** [comment]
> 

@landonr hehe yeah maybe we should use something like clang-format for this kind of stuff. We could either put a .clang-format file in the repo root or use the defaults.

**Comment by landonr** [comment]
ill check that out thanks

**Comment by landonr** [comment]
@abroooo woot i copied the esphome config for clang format and it's looking good. nice suggestion

**Comment by abroooo** [comment]
> @abroooo woot i copied the esphome config for clang format and it's looking good. nice suggestion

That's awesome 💪

**Pull request merged**
