### PR TITLE
Config examples

### PR DESCRIPTION
**Pull request by Carunga**
Added examples to the docs of the config bits I could not figure out myself. And added the player state "off". I failed to do that as an own pull request.

### CODE REVIEW

**Comment by landonr** [comment]
cool the "off" stuff helps with LG webos tvs but I don't think we can close #26 yet

i think the branch is failing because you added spaces instead of tabs (or the opposite). if you click on the details of the failed check you can see it's trying to remove and add the same line here
```
-      mediaArtist = "";     
+      mediaArtist = "";
```

**Comment by Carunga** [comment]
tried again, copied directly from the lines above, same result.

#26 cannot be closed, no. in my install i changed the command names. a more generic solution might be beyond what i can do.

**Comment by landonr** [comment]
can you try running `clang-format esphomeRemote/*.h --style=file:.clang-format --i`

**Comment by landonr** [comment]
yes brotherman!

**Pull request merged**
